name: gen_ui
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  genui: ^0.10.1
  http: ^1.6.0
  json_schema_builder: ^0.1.6
  a2ui_core: ^0.1.0
  flutter_markdown_plus: ^1.0.12
  flutter_spinkit: ^5.2.2
  shared_preferences: ^2.5.5
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/.env

